CREATE TABLE usuarios (
  id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  usuario VARCHAR(50) NOT NULL,
  contrasena VARCHAR(250) NOT NULL,
  email VARCHAR(200) DEFAULT NULL,
  full_name VARCHAR(150) DEFAULT NULL,
  privilegio VARCHAR(20) DEFAULT NULL,
  pictureURL VARCHAR(100) CHARACTER SET utf16 COLLATE utf16_spanish2_ci DEFAULT NULL
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT = 'tabla de usuarios';

CREATE TABLE configs (
  id INT(11) NOT NULL PRIMARY KEY,
  clase VARCHAR(100) DEFAULT NULL,
  dias VARCHAR(250) DEFAULT NULL,
  hora VARCHAR(200) DEFAULT NULL,
  aimharder_user VARCHAR(200) DEFAULT NULL,
  aimharder_pass VARCHAR(200) DEFAULT NULL,
  FOREIGN KEY (id) REFERENCES usuarios(id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT = 'tabla de configs';
